### ISSUE TITLE
HGIOURS Surveys not being created correctly

### ISSUE THREAD

**Issue by mark-cunningham** [mark-cunningham/Impact#10]
Something odd when creating a HGOURS survey.  I created the evaluations and completed various surveys.  Went back to dashboard and there were 2 identical surveys.  One had data in it, the other did not. Screenshot 4

![image](https://user-images.githubusercontent.com/11067443/42732864-be4a9ce0-8820-11e8-9a2a-6cb4369b010a.png)

Something odd when creating a HGOURS survey.  I created the evaluations and completed various surveys.  Went back to dashboard and there were 2 identical surveys.  One had data in it, the other did not. Screenshot 4

![image](https://user-images.githubusercontent.com/11067443/42732865-c680da14-8820-11e8-8970-f61d04b60d51.png)

**Comment by mark-cunningham** [comment]
I have tested this and am unable to recreate this bug. The time stamps of the two 'identical' surveys are 09:05:49 and 09:06:18. It's unlikely that the system could have created two HGIOURS surveys 30 seconds apart.

However, if you choose Save Priorities and Exit, and then press back, and the hit Save Priorities and Exit again, it will create a second identical survey.

I think this is probably what has happened.

**Comment by waitalan** [comment]
Okay - that makes sense.  I can't remember if that is what I did but it is likely I was using a combination of back and other buttons to navigate.  Also when working quickly, that is more likely to be the kind of mistake I would make.  If it happens again I will report.
